
services:

  backend:
    build:
      context: ./backend
      target: development

    command: npm run dev

    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env


  frontend:
    build:
      context: ./frontend
      target: development

    command: npm run dev -- --host

    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

    ports:
      - "5173:5173"