
services:

  backend:
    build:
      context: ./backend
      target: production

    container_name: github-commits-backend

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env


  frontend:
    build:
      context: ./frontend
      target: production
      args:
        VITE_API_BASE_URL: http://localhost:3000/api


    container_name: github-commits-frontend

    ports:
      - "8080:80"